#!/usr/bin/env zsh

typeset -gr CONFIG_ACTION_SCRIPT_DIR="$(dirname $(readlink -f $0))/config-actions"
typeset -gr INSTALL_ACTION_SCRIPT_DIR="$(dirname $(readlink -f $0))/install-actions"
typeset -gr ASSET_DIR="$(dirname $(readlink -f $0))/assets"

typeset -gr INITIAL_RUN="$1"
typeset -gr SCRIPT_DEBUG="true"

# validate locations before doing anything
if [[ ! -d $CONFIG_ACTION_SCRIPT_DIR ]]; then
    echo "ERROR: Config action script directory not found: $CONFIG_ACTION_SCRIPT_DIR"
    exit 1
fi

if [[ ! -d $INSTALL_ACTION_SCRIPT_DIR ]]; then
    echo "ERROR: Install action script directory not found: $INSTALL_ACTION_SCRIPT_DIR"
    exit 1
fi

if [[ ! -d $ASSET_DIR ]]; then
    echo "ERROR: Asset directory not found: $ASSET_DIR"
    exit 1
fi

echo "$ASSETS_DIR/logger"
source "$ASSETS_DIR/logger"

# usage: configure <topic>
function configure() {
    if [ ! -f "$CONFIG_ACTION_SCRIPT_DIR/$1" ]; then
        log_err "The file '$CONFIG_ACTION_SCRIPT_DIR/$1' does not exist. Skipping."
    else
        zsh "$CONFIG_ACTION_SCRIPT_DIR/$1" $SCRIPT_DEBUG || log_err "Failed to execute script: '$1'"
    fi
}

# usage: install <topic>
function install() {
    if [ ! -f "$INSTALL_ACTION_SCRIPT_DIR/$1" ]; then
        log_err "The file '$INSTALL_ACTION_SCRIPT_DIR/$1' does not exist. Skipping."
    else
        zsh "$INSTALL_ACTION_SCRIPT_DIR/$1" $SCRIPT_DEBUG || log_err "Failed to execute script: '$1'"
    fi
}


# on initial run, it is run with sudo - keep that alive
if [[ $INITIAL_RUN == "true" ]]; then
    log_dbg "Initial run detected. Running with sudo."
    sudo -v
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
fi

configure "world"
