# Appearance
# set -g status-bg "#0087af"  # Default status bar background
# set -g status-fg "default" # Default foreground

# Dynamically update status bar for the 'danger' session
set-hook -g session-created 'if-shell "[ #{session_name} = danger ]" "set -g status-style bg=red,fg=white"'
set-hook -g session-renamed 'if-shell -b "[ \"#{session_name}\" = \"danger\" ]" "set -g status-style bg=red,fg=white"'
# "set -g status-bg red"'
# Dynamically update status bar for the 'main' session
set-hook -g session-created 'if-shell "[ #{session_name} = main ]" "set -g status-style bg=\"#0087af\",fg=black"'
set-hook -g session-renamed 'if-shell -b "[ \"#{session_name}\" = \"main\" ]" "set -g status-style bg=\"#0087af\",fg=black"'

# Functionality
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1        # tmux window numbering starts at 1
setw -g pane-base-index 1  # Pane numbering starts at 1
