#!/usr/bin/env zsh

typeset -r SCRIPT_DEBUG="$1"
typeset -r ASSETS_DIR="$(dirname $(dirname $(realpath $0)))/assets"
typeset -r FILENAME="$(basename $0)"

source "$ASSETS_DIR/logger"
source "$ASSETS_DIR/macos-utils"


log_dbg "$FILENAME" "Starting script"


# actions here


log_dbg "$FILENAME" "Finishing script"
log_good "$FILENAME" "Setup complete!"